// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkfxydlqrflklnvnrsab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrZnh5ZGxxcmZsa2xudm5yc2FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzcwMTQsImV4cCI6MjA2NTY1MzAxNH0.2dJTVPT0PJ6OYN3LB4JL-u9CFbxFHK4VEL_mY85hlig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});